---
dependency:
  name: galaxy
  options:
    ignore_errors: true
    ignore_certs: true
    role-file: molecule/requirements.yml
    requirements-file: molecule/requirements.yml
driver:
  name: default
platforms:
  - name: instance
    image: quay.io/centos/centos:stream8
provisioner:
  name: ansible
  env:
    ANSIBLE_COLLECTIONS_PATH: ${HOME}/.ansible/collections

